site_name: geomapdemo

site_url: https://zyang91.github.io/geomapdemo

repo_url: https://github.com/zyang91/geomapdemo

theme:
    palette:
        scheme: preference
    name: material
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.instant
        - search.highlight
        # - navigation.expand
        # - navigation.tabs
    custom_dir: "docs/overrides"

plugins:
    - search
    - mkdocstrings
    - git-revision-date
    - mkdocs-jupyter:
          include_source: True
          execute: True
        #   ignore_h1_titles: True
        #   execute: True
        #   execute_ignore: "*.ipynb"
          
markdown_extensions:
    - attr_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

# extra:
#     analytics:
#         provider: google
#         property: UA-XXXXXXXXX-X

nav:
    - Home: index.md
    - Code of conduct: code_of_conduct.md
    - Statement of need: Statement_of_need.md
    - Installation: installation.md
    - Usage: usage.md
    - Contributing: contributing.md
    - FAQ: faq.md
    - Changelog: changelog.md
    - Report Issues: https://github.com/zyang91/geomapdemo/issues
    - Example:
        - examples/intro.ipynb
        - examples/folium.ipynb
        - examples/chart.ipynb
        - examples/chart_Example2.ipynb
        - examples/geomapdemo.ipynb
        - examples/test-folium.ipynb
        - examples/add_geojson.ipynb
        - examples/add_choropleth_map.ipynb
    - API Reference:
          - geomapdemo module: geomapdemo.md
          - foliumap module: foliumap.md
          - chart module: chart.md
